### ISSUE TITLE
Model run gives java.lang.NullPointerException

### ISSUE THREAD

**Issue by marisn** [CRAFTY-ABM/CRAFTY_v2#5]
Attempt to run simulation with default values of "data-DE_3kmgrid" model gives continuous output with errors:
```
------------------- Start of Tick  |2020| -------------------
INFO : [ModelRunner] - Cells.updateCapitals  
INFO : [ReaderFile] - Importing data for Capitals from : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/capitals/ssp1a26/DE_capitals_ssp1a26_2020.csv...  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Water/ssp1a26/Water_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: Water[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Water/ssp1a26/Water_Year_2020.csv]  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Urban/ssp1a26/UrbanMask_SSP1a_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: Urban[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Urban/ssp1a26/UrbanMask_SSP1a_Year_2020.csv]  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/ProtectedAreas_BfN/ssp1a26/ProtectedAreas_BfN_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: ProtectedAreas_BfN[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/ProtectedAreas_BfN/ssp1a26/ProtectedAreas_BfN_Year_2020.csv]  
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.concurrent.ForkJoinTask.getException(ForkJoinTask.java:557)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:573)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:663)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:677)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:264)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:785)
	at model.RegionalModelRunner.productivityForAll(RegionalModelRunner.java:78)
	at model.RegionalModelRunner.regionalSupply(RegionalModelRunner.java:121)
	at model.ModelRunner.lambda$1(ModelRunner.java:90)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4785)
	at model.ModelRunner.go(ModelRunner.java:89)
	at fxmlControllers.ModelRunnerController.oneStep(ModelRunnerController.java:162)
	at fxmlControllers.ModelRunnerController.lambda$5(ModelRunnerController.java:221)
	at javafx.graphics@22.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@22.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@22.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@22.0.2/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@22.0.2/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.NullPointerException
INFO : [CsvTools] - writing CSV file: /home/abm/crafty_projects/data-DE_3kmgrid/output/ssp1a26/My Project/ssp1a26-AggregateAFTComposition.csv  
INFO : [CsvTools] - Writing CSV file...  Done  
INFO : [CsvTools] - writing CSV file: /home/abm/crafty_projects/data-DE_3kmgrid/output/ssp1a26/My Project/ssp1a26-AggregateServiceDemand.csv  
INFO : [CsvTools] - Writing CSV file...  Done  
Delay For Last Tick=  300.0 ms Delay For Next Tick 300 ms
------------------- Start of Tick  |2020| -------------------
INFO : [ModelRunner] - Cells.updateCapitals  
INFO : [ReaderFile] - Importing data for Capitals from : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/capitals/ssp1a26/DE_capitals_ssp1a26_2020.csv...  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Water/ssp1a26/Water_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: Water[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Water/ssp1a26/Water_Year_2020.csv]  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Urban/ssp1a26/UrbanMask_SSP1a_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: Urban[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Urban/ssp1a26/UrbanMask_SSP1a_Year_2020.csv]  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/ProtectedAreas_BfN/ssp1a26/ProtectedAreas_BfN_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: ProtectedAreas_BfN[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/ProtectedAreas_BfN/ssp1a26/ProtectedAreas_BfN_Year_2020.csv]  
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
INFO : [CsvTools] - writing CSV file: /home/abm/crafty_projects/data-DE_3kmgrid/output/ssp1a26/My Project/ssp1a26-AggregateAFTComposition.csv  
INFO : [CsvTools] - Writing CSV file...  Done  
INFO : [CsvTools] - writing CSV file: /home/abm/crafty_projects/data-DE_3kmgrid/output/ssp1a26/My Project/ssp1a26-AggregateServiceDemand.csv  
INFO : [CsvTools] - Writing CSV file...  Done  
Delay For Last Tick=  300.0 ms Delay For Next Tick 300 ms
------------------- Start of Tick  |2020| -------------------
INFO : [ModelRunner] - Cells.updateCapitals  
INFO : [ReaderFile] - Importing data for Capitals from : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/capitals/ssp1a26/DE_capitals_ssp1a26_2020.csv...  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Water/ssp1a26/Water_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: Water[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Water/ssp1a26/Water_Year_2020.csv]  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Urban/ssp1a26/UrbanMask_SSP1a_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: Urban[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/Urban/ssp1a26/UrbanMask_SSP1a_Year_2020.csv]  
INFO : [ReaderFile] - Reading : /home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/ProtectedAreas_BfN/ssp1a26/ProtectedAreas_BfN_Year_2020.csv  
INFO : [MaskRestrictionDataLoader] - Update Mask: ProtectedAreas_BfN[/home/abm/crafty_projects/data-DE_3kmgrid/worlds/LandUseControl/ProtectedAreas_BfN/ssp1a26/ProtectedAreas_BfN_Year_2020.csv]  
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
INFO : [CsvTools] - writing CSV file: /home/abm/crafty_projects/data-DE_3kmgrid/output/ssp1a26/My Project/ssp1a26-AggregateAFTComposition.csv  
INFO : [CsvTools] - Writing CSV file...  Done  
INFO : [CsvTools] - writing CSV file: /home/abm/crafty_projects/data-DE_3kmgrid/output/ssp1a26/My Project/ssp1a26-AggregateServiceDemand.csv  
INFO : [CsvTools] - Writing CSV file...  Done  
Delay For Last Tick=  300.0 ms Delay For Next Tick 300 ms
```

**Comment by m-byari** [comment]
Resolved
